# Generated by Django 4.1.1 on 2023-02-02 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('dob', models.DateField(null=True)),
                ('mobile', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.IntegerField(null=True)),
                ('bookname', models.CharField(max_length=255)),
                ('bookauthor', models.CharField(max_length=255)),
                ('price', models.IntegerField(null=True)),
                ('buyer_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('dob', models.DateField(null=True)),
                ('mobile', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.IntegerField(null=True)),
                ('bookname', models.CharField(max_length=255)),
                ('bookauthor', models.CharField(max_length=255)),
                ('bookdescription', models.CharField(max_length=255)),
                ('bookrating', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('seller_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyLib.sellers')),
            ],
        ),
    ]
